# Generated by Django 4.1.5 on 2023-06-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('foto', models.ImageField(null=True, upload_to='foto')),
                ('publicar', models.BooleanField(default=False)),
                ('comentario', models.TextField(default='s/c')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCaos.categoria')),
            ],
        ),
    ]
