# Generated by Django 4.2.1 on 2023-07-02 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webCaos', '0003_producto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('idGaleria', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='foto')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCaos.noticia')),
            ],
        ),
    ]
